name: Build Firezone Client

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install frontend dependencies
        run:  npm install
              npm vite build

      - name: Build client
        run: cargo build -p firezone-gui-client --all-targets
        working-directory: ./rust/gui-client
